- title: "医療研究の実施"
  description: "最先端の医学・医療分野における基礎研究から臨床研究まで、包括的な研究活動を通じて新たな治療法と診断技術の開発を推進しています。"

- title: "医療・介護サービス開発"
  description: "医療・障害者格差の是正と医療・介護アクセス向上を目指し、革新的なサービスの開発・運用を行い、すべての人が必要な支援を受けられる環境を整備します。"

- title: "医療イノベーション創出"
  description: "研究成果の実用化を通じて医療イノベーションを創出し、新しい医療技術やサービスの社会実装を支援します。"

- title: "国際医療協力"
  description: "グローバルな医療課題の解決に向けて、国際的なパートナーシップを構築し、知識と技術の共有を通じて世界の健康増進に貢献します。"

- title: "啓発・教育活動"
  description: "医学・医療分野の知識普及と障害者理解の促進を目的とした啓発・教育プログラムを展開し、社会全体の意識向上を図ります。"
